// Code generated by ogen, DO NOT EDIT.
package oas

type FriendsUserIDGetRes interface {
	friendsUserIDGetRes()
}

type FriendsUserIDPostRes interface {
	friendsUserIDPostRes()
}

type LoginPostRes interface {
	loginPostRes()
}

type ProfileUserIDGetRes interface {
	profileUserIDGetRes()
}

type ProfileUserIDPostRes interface {
	profileUserIDPostRes()
}

type RegisterPostRes interface {
	registerPostRes()
}

type UserLoginGetRes interface {
	userLoginGetRes()
}
