// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerHttpAuthentication handles bearerHttpAuthentication security.
	// Bearer token using a JWT.
	HandleBearerHttpAuthentication(ctx context.Context, operationName OperationName, t BearerHttpAuthentication) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

func (s *Server) securityBearerHttpAuthentication(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerHttpAuthentication
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	rctx, err := s.sec.HandleBearerHttpAuthentication(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerHttpAuthentication provides bearerHttpAuthentication security value.
	// Bearer token using a JWT.
	BearerHttpAuthentication(ctx context.Context, operationName OperationName) (BearerHttpAuthentication, error)
}

func (s *Client) securityBearerHttpAuthentication(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerHttpAuthentication(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerHttpAuthentication\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
