// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	FriendsUserIDGetOperation  OperationName = "FriendsUserIDGet"
	FriendsUserIDPostOperation OperationName = "FriendsUserIDPost"
	LoginPostOperation         OperationName = "LoginPost"
	ProfileUserIDGetOperation  OperationName = "ProfileUserIDGet"
	ProfileUserIDPostOperation OperationName = "ProfileUserIDPost"
	RegisterPostOperation      OperationName = "RegisterPost"
	UserLoginGetOperation      OperationName = "UserLoginGet"
	WhoamiGetOperation         OperationName = "WhoamiGet"
)
