services:
  gateway-service:
    restart: always
    image: gateway-service
    build: ./gateway_service
    ports:
      - "8080:8080"
    depends_on:
      - users-service

  users-service:
    restart: always
    image: users-service
    environment:
      POSTGRES_HOST: users_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: usersservice
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: users
    build: ./users_service
    depends_on:
      - users_postgres

  posts-service:
    restart: always
    image: posts-service
    environment:
      POSTGRES_HOST: posts_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postsservice
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: posts
    build: ./posts_service
    depends_on:
      - posts_postgres

  users_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: usersservice
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: users
    volumes:
      - users_data:/var/lib/postgresql/data

  posts_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postsservice
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: posts
    volumes:
      - posts_data:/var/lib/postgresql/data

volumes:
  users_data:
    driver: local
  posts_data:
    driver: local

