// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *CreateUserRequest) setDefaults() {
	{
		val := RootFlag(false)
		s.Root.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ProfileInfo) setDefaults() {
	{
		val := RootFlag(false)
		s.Root = val
	}
}
