// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: posts.proto

package posts_grpc

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_Bad        Code = 0
	Code_Ok         Code = 200
	Code_BadRequest Code = 400
	Code_Forbidden  Code = 403
	Code_NotFound   Code = 404
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:   "Bad",
		200: "Ok",
		400: "BadRequest",
		403: "Forbidden",
		404: "NotFound",
	}
	Code_value = map[string]int32{
		"Bad":        0,
		"Ok":         200,
		"BadRequest": 400,
		"Forbidden":  403,
		"NotFound":   404,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_posts_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_posts_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{0}
}

type PostId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostId) Reset() {
	*x = PostId{}
	mi := &file_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostId) ProtoMessage() {}

func (x *PostId) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostId.ProtoReflect.Descriptor instead.
func (*PostId) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{0}
}

func (x *PostId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *PostId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,5,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	PublishDate   *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	LastModify    *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_modify,json=lastModify,proto3" json:"last_modify,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetId() *PostId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Post) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Post) GetPublishDate() *timestamp.Timestamp {
	if x != nil {
		return x.PublishDate
	}
	return nil
}

func (x *Post) GetLastModify() *timestamp.Timestamp {
	if x != nil {
		return x.LastModify
	}
	return nil
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PostUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *PostId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewTitle      string                 `protobuf:"bytes,2,opt,name=new_title,json=newTitle,proto3" json:"new_title,omitempty"`
	NewContent    string                 `protobuf:"bytes,3,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,5,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	ChangePrivate bool                   `protobuf:"varint,6,opt,name=change_private,json=changePrivate,proto3" json:"change_private,omitempty"`
	AddTags       []string               `protobuf:"bytes,7,rep,name=add_tags,json=addTags,proto3" json:"add_tags,omitempty"`
	RemoveTags    []string               `protobuf:"bytes,8,rep,name=remove_tags,json=removeTags,proto3" json:"remove_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdate) Reset() {
	*x = PostUpdate{}
	mi := &file_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdate) ProtoMessage() {}

func (x *PostUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdate.ProtoReflect.Descriptor instead.
func (*PostUpdate) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{2}
}

func (x *PostUpdate) GetId() *PostId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PostUpdate) GetNewTitle() string {
	if x != nil {
		return x.NewTitle
	}
	return ""
}

func (x *PostUpdate) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *PostUpdate) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *PostUpdate) GetChangePrivate() bool {
	if x != nil {
		return x.ChangePrivate
	}
	return false
}

func (x *PostUpdate) GetAddTags() []string {
	if x != nil {
		return x.AddTags
	}
	return nil
}

func (x *PostUpdate) GetRemoveTags() []string {
	if x != nil {
		return x.RemoveTags
	}
	return nil
}

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsRoot        bool                   `protobuf:"varint,2,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{3}
}

func (x *Actor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Actor) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreatePostRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=posts.Code" json:"code,omitempty"`
	Post          *Post                  `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePostResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Bad
}

func (x *CreatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *PostUpdate            `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePostRequest) GetUpdate() *PostUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdatePostRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=posts.Code" json:"code,omitempty"`
	Post          *Post                  `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_posts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePostResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Bad
}

func (x *UpdatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *PostId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_posts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostRequest) GetId() *PostId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DeletePostRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=posts.Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_posts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePostResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Bad
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *PostId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_posts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostRequest) GetId() *PostId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetPostRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=posts.Code" json:"code,omitempty"`
	Post          *Post                  `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_posts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Bad
}

func (x *GetPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type ListPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageLimit     uint32                 `protobuf:"varint,2,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	WithHidden    bool                   `protobuf:"varint,3,opt,name=with_hidden,json=withHidden,proto3" json:"with_hidden,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_posts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{12}
}

func (x *ListPostsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsRequest) GetPageLimit() uint32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

func (x *ListPostsRequest) GetWithHidden() bool {
	if x != nil {
		return x.WithHidden
	}
	return false
}

func (x *ListPostsRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=posts.Code" json:"code,omitempty"`
	Posts         []*Post                `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	From          uint32                 `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To            uint32                 `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	Total         uint32                 `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_posts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{13}
}

func (x *ListPostsResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Bad
}

func (x *ListPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ListPostsResponse) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ListPostsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_posts_proto protoreflect.FileDescriptor

const file_posts_proto_rawDesc = "" +
	"\n" +
	"\vposts.proto\x12\x05posts\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x06PostId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x02\n" +
	"\x04Post\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.posts.PostIdR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x1d\n" +
	"\n" +
	"is_private\x18\x05 \x01(\bR\tisPrivate\x12=\n" +
	"\fpublish_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishDate\x12;\n" +
	"\vlast_modify\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastModify\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"\xeb\x01\n" +
	"\n" +
	"PostUpdate\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.posts.PostIdR\x02id\x12\x1b\n" +
	"\tnew_title\x18\x02 \x01(\tR\bnewTitle\x12\x1f\n" +
	"\vnew_content\x18\x03 \x01(\tR\n" +
	"newContent\x12\x1d\n" +
	"\n" +
	"is_private\x18\x05 \x01(\bR\tisPrivate\x12%\n" +
	"\x0echange_private\x18\x06 \x01(\bR\rchangePrivate\x12\x19\n" +
	"\badd_tags\x18\a \x03(\tR\aaddTags\x12\x1f\n" +
	"\vremove_tags\x18\b \x03(\tR\n" +
	"removeTags\"9\n" +
	"\x05Actor\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ais_root\x18\x02 \x01(\bR\x06isRoot\"\x9a\x01\n" +
	"\x11CreatePostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\"\n" +
	"\x05actor\x18\x06 \x01(\v2\f.posts.ActorR\x05actor\"V\n" +
	"\x12CreatePostResponse\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\x0e2\v.posts.CodeR\x04code\x12\x1f\n" +
	"\x04post\x18\x02 \x01(\v2\v.posts.PostR\x04post\"b\n" +
	"\x11UpdatePostRequest\x12)\n" +
	"\x06update\x18\x01 \x01(\v2\x11.posts.PostUpdateR\x06update\x12\"\n" +
	"\x05actor\x18\x02 \x01(\v2\f.posts.ActorR\x05actor\"V\n" +
	"\x12UpdatePostResponse\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\x0e2\v.posts.CodeR\x04code\x12\x1f\n" +
	"\x04post\x18\x02 \x01(\v2\v.posts.PostR\x04post\"V\n" +
	"\x11DeletePostRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.posts.PostIdR\x02id\x12\"\n" +
	"\x05actor\x18\x02 \x01(\v2\f.posts.ActorR\x05actor\"5\n" +
	"\x12DeletePostResponse\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\x0e2\v.posts.CodeR\x04code\"S\n" +
	"\x0eGetPostRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.posts.PostIdR\x02id\x12\"\n" +
	"\x05actor\x18\x02 \x01(\v2\f.posts.ActorR\x05actor\"S\n" +
	"\x0fGetPostResponse\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\x0e2\v.posts.CodeR\x04code\x12\x1f\n" +
	"\x04post\x18\x02 \x01(\v2\v.posts.PostR\x04post\"\x8a\x01\n" +
	"\x10ListPostsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x02 \x01(\rR\tpageLimit\x12\x1f\n" +
	"\vwith_hidden\x18\x03 \x01(\bR\n" +
	"withHidden\x12\"\n" +
	"\x05actor\x18\x04 \x01(\v2\f.posts.ActorR\x05actor\"\x91\x01\n" +
	"\x11ListPostsResponse\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\x0e2\v.posts.CodeR\x04code\x12!\n" +
	"\x05posts\x18\x02 \x03(\v2\v.posts.PostR\x05posts\x12\x12\n" +
	"\x04from\x18\x03 \x01(\rR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\rR\x02to\x12\x14\n" +
	"\x05total\x18\x05 \x01(\rR\x05total*H\n" +
	"\x04Code\x12\a\n" +
	"\x03Bad\x10\x00\x12\a\n" +
	"\x02Ok\x10\xc8\x01\x12\x0f\n" +
	"\n" +
	"BadRequest\x10\x90\x03\x12\x0e\n" +
	"\tForbidden\x10\x93\x03\x12\r\n" +
	"\bNotFound\x10\x94\x032\xd0\x02\n" +
	"\vPostService\x12A\n" +
	"\n" +
	"CreatePost\x12\x18.posts.CreatePostRequest\x1a\x19.posts.CreatePostResponse\x12A\n" +
	"\n" +
	"UpdatePost\x12\x18.posts.UpdatePostRequest\x1a\x19.posts.UpdatePostResponse\x12A\n" +
	"\n" +
	"DeletePost\x12\x18.posts.DeletePostRequest\x1a\x19.posts.DeletePostResponse\x128\n" +
	"\aGetPost\x12\x15.posts.GetPostRequest\x1a\x16.posts.GetPostResponse\x12>\n" +
	"\tListPosts\x12\x17.posts.ListPostsRequest\x1a\x18.posts.ListPostsResponseB\x0fZ\r./;posts_grpcb\x06proto3"

var (
	file_posts_proto_rawDescOnce sync.Once
	file_posts_proto_rawDescData []byte
)

func file_posts_proto_rawDescGZIP() []byte {
	file_posts_proto_rawDescOnce.Do(func() {
		file_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)))
	})
	return file_posts_proto_rawDescData
}

var file_posts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_posts_proto_goTypes = []any{
	(Code)(0),                   // 0: posts.Code
	(*PostId)(nil),              // 1: posts.PostId
	(*Post)(nil),                // 2: posts.Post
	(*PostUpdate)(nil),          // 3: posts.PostUpdate
	(*Actor)(nil),               // 4: posts.Actor
	(*CreatePostRequest)(nil),   // 5: posts.CreatePostRequest
	(*CreatePostResponse)(nil),  // 6: posts.CreatePostResponse
	(*UpdatePostRequest)(nil),   // 7: posts.UpdatePostRequest
	(*UpdatePostResponse)(nil),  // 8: posts.UpdatePostResponse
	(*DeletePostRequest)(nil),   // 9: posts.DeletePostRequest
	(*DeletePostResponse)(nil),  // 10: posts.DeletePostResponse
	(*GetPostRequest)(nil),      // 11: posts.GetPostRequest
	(*GetPostResponse)(nil),     // 12: posts.GetPostResponse
	(*ListPostsRequest)(nil),    // 13: posts.ListPostsRequest
	(*ListPostsResponse)(nil),   // 14: posts.ListPostsResponse
	(*timestamp.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_posts_proto_depIdxs = []int32{
	1,  // 0: posts.Post.id:type_name -> posts.PostId
	15, // 1: posts.Post.publish_date:type_name -> google.protobuf.Timestamp
	15, // 2: posts.Post.last_modify:type_name -> google.protobuf.Timestamp
	1,  // 3: posts.PostUpdate.id:type_name -> posts.PostId
	4,  // 4: posts.CreatePostRequest.actor:type_name -> posts.Actor
	0,  // 5: posts.CreatePostResponse.code:type_name -> posts.Code
	2,  // 6: posts.CreatePostResponse.post:type_name -> posts.Post
	3,  // 7: posts.UpdatePostRequest.update:type_name -> posts.PostUpdate
	4,  // 8: posts.UpdatePostRequest.actor:type_name -> posts.Actor
	0,  // 9: posts.UpdatePostResponse.code:type_name -> posts.Code
	2,  // 10: posts.UpdatePostResponse.post:type_name -> posts.Post
	1,  // 11: posts.DeletePostRequest.id:type_name -> posts.PostId
	4,  // 12: posts.DeletePostRequest.actor:type_name -> posts.Actor
	0,  // 13: posts.DeletePostResponse.code:type_name -> posts.Code
	1,  // 14: posts.GetPostRequest.id:type_name -> posts.PostId
	4,  // 15: posts.GetPostRequest.actor:type_name -> posts.Actor
	0,  // 16: posts.GetPostResponse.code:type_name -> posts.Code
	2,  // 17: posts.GetPostResponse.post:type_name -> posts.Post
	4,  // 18: posts.ListPostsRequest.actor:type_name -> posts.Actor
	0,  // 19: posts.ListPostsResponse.code:type_name -> posts.Code
	2,  // 20: posts.ListPostsResponse.posts:type_name -> posts.Post
	5,  // 21: posts.PostService.CreatePost:input_type -> posts.CreatePostRequest
	7,  // 22: posts.PostService.UpdatePost:input_type -> posts.UpdatePostRequest
	9,  // 23: posts.PostService.DeletePost:input_type -> posts.DeletePostRequest
	11, // 24: posts.PostService.GetPost:input_type -> posts.GetPostRequest
	13, // 25: posts.PostService.ListPosts:input_type -> posts.ListPostsRequest
	6,  // 26: posts.PostService.CreatePost:output_type -> posts.CreatePostResponse
	8,  // 27: posts.PostService.UpdatePost:output_type -> posts.UpdatePostResponse
	10, // 28: posts.PostService.DeletePost:output_type -> posts.DeletePostResponse
	12, // 29: posts.PostService.GetPost:output_type -> posts.GetPostResponse
	14, // 30: posts.PostService.ListPosts:output_type -> posts.ListPostsResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_posts_proto_init() }
func file_posts_proto_init() {
	if File_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_proto_goTypes,
		DependencyIndexes: file_posts_proto_depIdxs,
		EnumInfos:         file_posts_proto_enumTypes,
		MessageInfos:      file_posts_proto_msgTypes,
	}.Build()
	File_posts_proto = out.File
	file_posts_proto_goTypes = nil
	file_posts_proto_depIdxs = nil
}
