name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Build Docker Compose
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up
